In [21]:
import pandas as pd

df = pd.read_csv("data/LBNL_file.csv", low_memory=False)


df.head()

,data_provider_1,data_provider_2,system_ID_1,system_ID_2,installation_date,system_size_DC,total_installed_price,rebate_or_grant,customer_segment,expansion_system,...,built_in_meter_inverter_1,built_in_meter_inverter_2,built_in_meter_inverter_3,output_capacity_inverter_1,output_capacity_inverter_2,output_capacity_inverter_3,DC_optimizer,inverter_loading_ratio,battery_rated_capacity_kW,battery_rated_capacity_kWh
0,Arkansas State Energy Office,-9999,-9999,-9999,29-Apr-2010 00:00:00,2.016,14558.0,0.0,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.178947,-9999.0,-9999.0
1,Arkansas State Energy Office,-9999,-9999,-9999,26-Apr-2010 00:00:00,3.360,26096.0,0.0,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.178947,-9999.0,-9999.0
2,Arkansas State Energy Office,-9999,-9999,-9999,20-Apr-2010 00:00:00,13.440,91139.0,0.0,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.178947,-9999.0,-9999.0
3,Arkansas State Energy Office,-9999,-9999,-9999,21-Apr-2010 00:00:00,5.520,40043.0,0.0,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.210526,-9999.0,-9999.0
4,Arkansas State Energy Office,-9999,-9999,-9999,22-Apr-2010 00:00:00,2.530,21497.0,0.0,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.210526,-9999.0,-9999.0

In [22]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 78 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   data_provider_1                  1000000 non-null  object
 1   data_provider_2                  1000000 non-null  object
 2   system_ID_1                      1000000 non-null  object
 3   system_ID_2                      1000000 non-null  object
 4   installation_date                1000000 non-null  object
 5   system_size_DC                   1000000 non-null  float64
 6   total_installed_price            1000000 non-null  float64
 7   rebate_or_grant                  1000000 non-null  float64
 8   customer_segment                 1000000 non-null  object
 9   expansion_system                 1000000 non-null  int64
 10  multiple_phase_system            1000000 non-null  int64
 11  new_construction                 1000000 non-null  int64
 12  tracking                         1000000 non-null  int64
 13  ground_mounted                   1000000 non-null  int64
 14  zip_code                         1000000 non-null  object
 15  city                             1000000 non-null  object
 16  state                            1000000 non-null  object
 17  utility_service_territory        1000000 non-null  object
 18  third_party_owned                1000000 non-null  int64
 19  installer_name                   1000000 non-null  object
 20  self_installed                   1000000 non-null  int64
 21  azimuth_1                        1000000 non-null  float64
 22  azimuth_2                        1000000 non-null  float64
 23  azimuth_3                        1000000 non-null  float64
 24  tilt_1                           1000000 non-null  float64
 25  tilt_2                           1000000 non-null  int64
 26  tilt_3                           1000000 non-null  int64
 27  module_manufacturer_1            1000000 non-null  object
 28  module_model_1                   1000000 non-null  object
 29  module_quantity_1                1000000 non-null  int64
 30  module_manufacturer_2            1000000 non-null  object
 31  module_model_2                   1000000 non-null  object
 32  module_quantity_2                1000000 non-null  int64
 33  module_manufacturer_3            1000000 non-null  object
 34  module_model_3                   1000000 non-null  object
 35  module_quantity_3                1000000 non-null  int64
 36  additional_modules               1000000 non-null  int64
 37  technology_module_1              1000000 non-null  object
 38  technology_module_2              1000000 non-null  object
 39  technology_module_3              1000000 non-null  int64
 40  BIPV_module_1                    1000000 non-null  int64
 41  BIPV_module_2                    1000000 non-null  int64
 42  BIPV_module_3                    1000000 non-null  int64
 43  bifacial_module_1                1000000 non-null  int64
 44  bifacial_module_2                1000000 non-null  int64
 45  bifacial_module_3                1000000 non-null  int64
 46  nameplate_capacity_module_1      1000000 non-null  float64
 47  nameplate_capacity_module_2      1000000 non-null  float64
 48  nameplate_capacity_module_3      1000000 non-null  int64
 49  efficiency_module_1              1000000 non-null  float64
 50  efficiency_module_2              1000000 non-null  float64
 51  efficiency_module_3              1000000 non-null  float64
 52  inverter_manufacturer_1          1000000 non-null  object
 53  inverter_model_1                 1000000 non-null  object
 54  inverter_quantity_1              1000000 non-null  int64
 55  inverter_manufacturer_2          1000000 non-null  object
 56  inverter_model_2                 1000000 non-null  object
 57  inverter_quantity_2              1000000 non-null  int64
 58  inverter_manufacturer_3          1000000 non-null  object
 59  inverter_model_3                 1000000 non-null  object
 60  inverter_quantity_3              1000000 non-null  int64
 61  additional_inverters             1000000 non-null  int64
 62  micro_inverter_1                 1000000 non-null  int64
 63  micro_inverter_2                 1000000 non-null  int64
 64  micro_inverter_3                 1000000 non-null  int64
 65  solar_storage_hybrid_inverter_1  1000000 non-null  int64
 66  solar_storage_hybrid_inverter_2  1000000 non-null  int64
 67  solar_storage_hybrid_inverter_3  1000000 non-null  int64
 68  built_in_meter_inverter_1        1000000 non-null  int64
 69  built_in_meter_inverter_2        1000000 non-null  int64
 70  built_in_meter_inverter_3        1000000 non-null  int64
 71  output_capacity_inverter_1       1000000 non-null  float64
 72  output_capacity_inverter_2       1000000 non-null  float64
 73  output_capacity_inverter_3       1000000 non-null  float64
 74  DC_optimizer                     1000000 non-null  int64
 75  inverter_loading_ratio           1000000 non-null  float64
 76  battery_rated_capacity_kW        1000000 non-null  float64
 77  battery_rated_capacity_kWh       1000000 non-null  float64
dtypes: float64(18), int64(35), object(25)
memory usage: 595.1+ MB

In [23]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
system_size_DC,1000000.0,-103.848630,1059.276396,-9999.0,3.900000,5.500000,7.700000,1.330561e+04
total_installed_price,1000000.0,29290.866715,174230.776901,-9999.0,9045.000000,20460.000000,31309.000000,6.150719e+07
rebate_or_grant,1000000.0,841.183410,19009.872435,-9999.0,0.000000,0.000000,0.000000,4.317390e+06
expansion_system,1000000.0,0.009305,0.096013,0.0,0.000000,0.000000,0.000000,1.000000e+00
multiple_phase_system,1000000.0,0.004546,0.067271,0.0,0.000000,0.000000,0.000000,1.000000e+00
new_construction,1000000.0,-7928.710328,4051.581257,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.000000e+00
tracking,1000000.0,-1005.494469,3007.154605,-9999.0,0.000000,0.000000,0.000000,1.000000e+00
ground_mounted,1000000.0,-2405.119393,4273.687924,-9999.0,0.000000,0.000000,0.000000,1.000000e+00
third_party_owned,1000000.0,-825.799579,2752.945805,-9999.0,0.000000,0.000000,1.000000,1.000000e+00
self_installed,1000000.0,-444.362165,2060.572183,-9999.0,0.000000,0.000000,0.000000,1.000000e+00
azimuth_1,1000000.0,-3026.225782,4735.312003,-9999.0,-9999.000000,170.000000,194.000000,3.600000e+02
azimuth_2,1000000.0,-9527.363641,2140.992057,-9999.0,-9999.000000,-9999.000000,-9999.000000,3.600000e+02
azimuth_3,1000000.0,-9873.629644,1123.107851,-9999.0,-9999.000000,-9999.000000,-9999.000000,3.600000e+02
tilt_1,1000000.0,-3123.249339,4648.704917,-9999.0,-9999.000000,18.000000,21.000000,9.000000e+01
tilt_2,1000000.0,-9535.011087,2105.591612,-9999.0,-9999.000000,-9999.000000,-9999.000000,9.000000e+01
tilt_3,1000000.0,-9875.618455,1104.949819,-9999.0,-9999.000000,-9999.000000,-9999.000000,9.000000e+01
module_quantity_1,1000000.0,-6.104299,702.346556,-9999.0,12.000000,18.000000,26.000000,3.165140e+05
module_quantity_2,1000000.0,-9860.605230,1171.384817,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.241600e+04
module_quantity_3,1000000.0,-9995.224404,197.179152,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.641300e+04
additional_modules,1000000.0,-10.288855,320.583317,-9999.0,0.000000,0.000000,0.000000,1.000000e+00
technology_module_3,1000000.0,-9999.000000,0.000000,-9999.0,-9999.000000,-9999.000000,-9999.000000,-9.999000e+03
BIPV_module_1,1000000.0,-599.485845,2373.799343,-9999.0,0.000000,0.000000,0.000000,1.000000e+00
BIPV_module_2,1000000.0,-9904.149399,969.234921,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.000000e+00
BIPV_module_3,1000000.0,-9984.971387,374.266749,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.000000e+00
bifacial_module_1,1000000.0,-526.406829,2233.035595,-9999.0,0.000000,0.000000,0.000000,1.000000e+00
bifacial_module_2,1000000.0,-9844.355460,1233.846589,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.000000e+00
bifacial_module_3,1000000.0,-9984.711429,377.713385,-9999.0,-9999.000000,-9999.000000,-9999.000000,0.000000e+00
nameplate_capacity_module_1,1000000.0,-683.270554,2997.311798,-9999.0,250.000000,270.000000,315.000000,8.640000e+02
nameplate_capacity_module_2,1000000.0,-9916.347664,916.873871,-9999.0,-9999.000000,-9999.000000,-9999.000000,8.640000e+02
nameplate_capacity_module_3,1000000.0,-9985.916454,365.897390,-9999.0,-9999.000000,-9999.000000,-9999.000000,8.640000e+02
efficiency_module_1,1000000.0,-942.717165,2922.175058,-9999.0,0.154668,0.169387,0.192114,2.272727e-01
efficiency_module_2,1000000.0,-9918.526749,893.414730,-9999.0,-9999.000000,-9999.000000,-9999.000000,2.269939e-01
efficiency_module_3,1000000.0,-9986.251073,356.813856,-9999.0,-9999.000000,-9999.000000,-9999.000000,2.207622e-01
inverter_quantity_1,1000000.0,-43.163896,709.401004,-9999.0,1.000000,1.000000,12.000000,5.680000e+03
inverter_quantity_2,1000000.0,-9650.042234,1835.235322,-9999.0,-9999.000000,-9999.000000,-9999.000000,2.880000e+02
inverter_quantity_3,1000000.0,-9982.437941,406.653509,-9999.0,-9999.000000,-9999.000000,-9999.000000,7.500000e+01
additional_inverters,1000000.0,-10.288668,320.583324,-9999.0,0.000000,0.000000,0.000000,1.000000e+00
micro_inverter_1,1000000.0,-57.669555,759.249063,-9999.0,0.000000,0.000000,1.000000,1.000000e+00
micro_inverter_2,1000000.0,-9638.724495,1863.495417,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.000000e+00
micro_inverter_3,1000000.0,-9970.762493,530.615743,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.000000e+00
solar_storage_hybrid_inverter_1,1000000.0,-1827.733896,3864.576055,-9999.0,0.000000,0.000000,0.000000,1.000000e+00
solar_storage_hybrid_inverter_2,1000000.0,-9699.999728,1703.028833,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.000000e+00
solar_storage_hybrid_inverter_3,1000000.0,-9999.000000,0.000000,-9999.0,-9999.000000,-9999.000000,-9999.000000,-9.999000e+03
built_in_meter_inverter_1,1000000.0,-996.420579,2995.807339,-9999.0,0.000000,0.000000,1.000000,1.000000e+00
built_in_meter_inverter_2,1000000.0,-9662.960282,1802.047426,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.000000e+00
built_in_meter_inverter_3,1000000.0,-9972.040919,518.512389,-9999.0,-9999.000000,-9999.000000,-9999.000000,1.000000e+00
output_capacity_inverter_1,1000000.0,-1701.538187,3761.985554,-9999.0,0.215000,3.000000,5.000000,1.100000e+03
output_capacity_inverter_2,1000000.0,-9698.522801,1707.800713,-9999.0,-9999.000000,-9999.000000,-9999.000000,8.000000e+02
output_capacity_inverter_3,1000000.0,-9977.219210,466.526509,-9999.0,-9999.000000,-9999.000000,-9999.000000,9.000000e+02
DC_optimizer,1000000.0,-49.532991,703.880420,-9999.0,0.000000,0.000000,1.000000,1.000000e+00
inverter_loading_ratio,1000000.0,-2467.060370,4311.635029,-9999.0,0.766667,1.073333,1.174603,1.500000e+00
battery_rated_capacity_kW,1000000.0,-9844.379240,1234.357423,-9999.0,-9999.000000,-9999.000000,-9999.000000,2.442240e+03
battery_rated_capacity_kWh,1000000.0,-9928.761157,835.865084,-9999.0,-9999.000000,-9999.000000,-9999.000000,2.000000e+03

In [24]:
df["system_size_DC"].value_counts()

-9999.00000    11308
 6.00000        6506
 5.04000        6431
 5.20000        5704
 3.00000        5453
               ...
 3.16250           1
 1.15830           1
 15.62804          1
 6.12370           1
 710.80000         1
Name: system_size_DC, Length: 36031, dtype: int64

In [25]:
df["output_capacity_inverter_3"].value_counts()

-9999.000    997825
 0.215          239
 3.000          216
 6.000          199
 5.000          193
              ...
 125.000          1
 9.994            1
 25.000           1
 2.962            1
 11.995           1
Name: output_capacity_inverter_3, Length: 102, dtype: int64

In [26]:
df["built_in_meter_inverter_3"].value_counts()

-9999    997304
 1         1777
 0          919
Name: built_in_meter_inverter_3, dtype: int64

In [27]:
df["state"].value_counts()

CA    998971
AZ       924
AR       105
Name: state, dtype: int64

In [28]:
df = df[df['system_size_DC'] != -9999]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 988692 entries, 0 to 999999
Data columns (total 78 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   data_provider_1                  988692 non-null  object
 1   data_provider_2                  988692 non-null  object
 2   system_ID_1                      988692 non-null  object
 3   system_ID_2                      988692 non-null  object
 4   installation_date                988692 non-null  object
 5   system_size_DC                   988692 non-null  float64
 6   total_installed_price            988692 non-null  float64
 7   rebate_or_grant                  988692 non-null  float64
 8   customer_segment                 988692 non-null  object
 9   expansion_system                 988692 non-null  int64
 10  multiple_phase_system            988692 non-null  int64
 11  new_construction                 988692 non-null  int64
 12  tracking                         988692 non-null  int64
 13  ground_mounted                   988692 non-null  int64
 14  zip_code                         988692 non-null  object
 15  city                             988692 non-null  object
 16  state                            988692 non-null  object
 17  utility_service_territory        988692 non-null  object
 18  third_party_owned                988692 non-null  int64
 19  installer_name                   988692 non-null  object
 20  self_installed                   988692 non-null  int64
 21  azimuth_1                        988692 non-null  float64
 22  azimuth_2                        988692 non-null  float64
 23  azimuth_3                        988692 non-null  float64
 24  tilt_1                           988692 non-null  float64
 25  tilt_2                           988692 non-null  int64
 26  tilt_3                           988692 non-null  int64
 27  module_manufacturer_1            988692 non-null  object
 28  module_model_1                   988692 non-null  object
 29  module_quantity_1                988692 non-null  int64
 30  module_manufacturer_2            988692 non-null  object
 31  module_model_2                   988692 non-null  object
 32  module_quantity_2                988692 non-null  int64
 33  module_manufacturer_3            988692 non-null  object
 34  module_model_3                   988692 non-null  object
 35  module_quantity_3                988692 non-null  int64
 36  additional_modules               988692 non-null  int64
 37  technology_module_1              988692 non-null  object
 38  technology_module_2              988692 non-null  object
 39  technology_module_3              988692 non-null  int64
 40  BIPV_module_1                    988692 non-null  int64
 41  BIPV_module_2                    988692 non-null  int64
 42  BIPV_module_3                    988692 non-null  int64
 43  bifacial_module_1                988692 non-null  int64
 44  bifacial_module_2                988692 non-null  int64
 45  bifacial_module_3                988692 non-null  int64
 46  nameplate_capacity_module_1      988692 non-null  float64
 47  nameplate_capacity_module_2      988692 non-null  float64
 48  nameplate_capacity_module_3      988692 non-null  int64
 49  efficiency_module_1              988692 non-null  float64
 50  efficiency_module_2              988692 non-null  float64
 51  efficiency_module_3              988692 non-null  float64
 52  inverter_manufacturer_1          988692 non-null  object
 53  inverter_model_1                 988692 non-null  object
 54  inverter_quantity_1              988692 non-null  int64
 55  inverter_manufacturer_2          988692 non-null  object
 56  inverter_model_2                 988692 non-null  object
 57  inverter_quantity_2              988692 non-null  int64
 58  inverter_manufacturer_3          988692 non-null  object
 59  inverter_model_3                 988692 non-null  object
 60  inverter_quantity_3              988692 non-null  int64
 61  additional_inverters             988692 non-null  int64
 62  micro_inverter_1                 988692 non-null  int64
 63  micro_inverter_2                 988692 non-null  int64
 64  micro_inverter_3                 988692 non-null  int64
 65  solar_storage_hybrid_inverter_1  988692 non-null  int64
 66  solar_storage_hybrid_inverter_2  988692 non-null  int64
 67  solar_storage_hybrid_inverter_3  988692 non-null  int64
 68  built_in_meter_inverter_1        988692 non-null  int64
 69  built_in_meter_inverter_2        988692 non-null  int64
 70  built_in_meter_inverter_3        988692 non-null  int64
 71  output_capacity_inverter_1       988692 non-null  float64
 72  output_capacity_inverter_2       988692 non-null  float64
 73  output_capacity_inverter_3       988692 non-null  float64
 74  DC_optimizer                     988692 non-null  int64
 75  inverter_loading_ratio           988692 non-null  float64
 76  battery_rated_capacity_kW        988692 non-null  float64
 77  battery_rated_capacity_kWh       988692 non-null  float64
dtypes: float64(18), int64(35), object(25)
memory usage: 595.9+ MB

In [29]:
df["state"].value_counts()

CA    987664
AZ       923
AR       105
Name: state, dtype: int64

In [30]:
import seaborn as sns

#df["customer_segment"] = df[df["customer_segment"].isin(["RES","COM"])]

In [31]:
df.filter(items=['output_capacity_inverter_1',
       'output_capacity_inverter_2', 'output_capacity_inverter_3']).max(1)

0            0.19
1            0.19
2            0.19
3            0.19
4            0.19
           ...
999995     250.00
999996   -9999.00
999997   -9999.00
999998   -9999.00
999999   -9999.00
Length: 988692, dtype: float64

In [32]:
#df_res = df_res.groupby(["customer_segment"])["state"].count()
#df_res

df

,data_provider_1,data_provider_2,system_ID_1,system_ID_2,installation_date,system_size_DC,total_installed_price,rebate_or_grant,customer_segment,expansion_system,...,built_in_meter_inverter_1,built_in_meter_inverter_2,built_in_meter_inverter_3,output_capacity_inverter_1,output_capacity_inverter_2,output_capacity_inverter_3,DC_optimizer,inverter_loading_ratio,battery_rated_capacity_kW,battery_rated_capacity_kWh
0,Arkansas State Energy Office,-9999,-9999,-9999,29-Apr-2010 00:00:00,2.016,14558.0,0.00,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.178947,-9999.0,-9999.0
1,Arkansas State Energy Office,-9999,-9999,-9999,26-Apr-2010 00:00:00,3.360,26096.0,0.00,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.178947,-9999.0,-9999.0
2,Arkansas State Energy Office,-9999,-9999,-9999,20-Apr-2010 00:00:00,13.440,91139.0,0.00,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.178947,-9999.0,-9999.0
3,Arkansas State Energy Office,-9999,-9999,-9999,21-Apr-2010 00:00:00,5.520,40043.0,0.00,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.210526,-9999.0,-9999.0
4,Arkansas State Energy Office,-9999,-9999,-9999,22-Apr-2010 00:00:00,2.530,21497.0,0.00,RES,0,...,0,-9999,-9999,0.19,-9999.0,-9999.0,0,1.210526,-9999.0,-9999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,Arizona Public Service,-9999,D1117,-9999,31-Dec-2008 00:00:00,710.800,5920000.0,0.00,NON-RES,0,...,1,-9999,-9999,250.00,-9999.0,-9999.0,0,-9999.000000,-9999.0,-9999.0
999996,Arizona Public Service,-9999,D1036,-9999,13-Nov-2008 00:00:00,32.000,264000.0,0.00,NON-RES,0,...,-9999,-9999,-9999,-9999.00,-9999.0,-9999.0,-9999,-9999.000000,-9999.0,-9999.0
999997,Arizona Public Service,-9999,D1575,-9999,14-May-2009 00:00:00,99.960,1172822.0,0.00,NON-RES,0,...,-9999,-9999,-9999,-9999.00,-9999.0,-9999.0,-9999,-9999.000000,-9999.0,-9999.0
999998,Arizona Public Service,-9999,R1286,-9999,09-Feb-2009 00:00:00,10.000,65006.0,30000.00,RES,0,...,-9999,-9999,-9999,-9999.00,-9999.0,-9999.0,-9999,-9999.000000,-9999.0,-9999.0
999999,Arizona Public Service,-9999,R1194,-9999,12-Jan-2009 00:00:00,5.760,39857.7,19928.85,RES,0,...,-9999,-9999,-9999,-9999.00,-9999.0,-9999.0,-9999,-9999.000000,-9999.0,-9999.0

In [56]:

df_test = df[["inverter_quantity_1", "inverter_quantity_2", "inverter_quantity_3","inverter_manufacturer_1","inverter_manufacturer_2","inverter_manufacturer_3"]]

df_test = df_test[(df_test["inverter_quantity_2"] != -9999.0) & (df_test["inverter_quantity_3"] != -9999.0 )]

df_test


#df.filter(items=['output_capacity_inverter_1',
      # 'output_capacity_inverter_2', 'output_capacity_inverter_3']).max(1)

,inverter_quantity_1,inverter_quantity_2,inverter_quantity_3,inverter_manufacturer_1,inverter_manufacturer_2,inverter_manufacturer_3
1719,5,2,1,-9999,SOLAREDGE TECHNOLOGIES LTD.,-9999
2799,5,3,11,Yaskawa Solectria Solar,Yaskawa Solectria Solar,Yaskawa Solectria Solar
3040,1,1,1,DELTA ELECTRONICS,-9999,DELTA ELECTRONICS
3811,6,4,1,Delta Electronics,Delta Electronics,Delta Electronics
4830,2,1,1,CHINT POWER SYSTEMS AMERICA,-9999,FRONIUS USA
...,...,...,...,...,...,...
996511,1,2,1,Schuco USA,ENPHASE ENERGY INC.,Schuco USA
997476,1,1,1,ABB,Power-One,ABB
997921,3,1,1,SMA America,SMA America,SMA America
998464,6,28,14,SMA America,SMA America,SMA America
998535,98,4,4,Enphase Energy,-9999,XANTREX TECHNOLOGY

In [62]:
#df.iloc[2799][70:91]

-9999    954254
 1        30651
 2         1580
 3          417
 4          253
          ...
 69           1
 136          1
 100          1
 44           1
 50           1
Name: inverter_quantity_2, Length: 65, dtype: int64